package com.lambdaexpressions.notificationfiltering;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

public class NotificationFiltering {

    public static void main(String[] args) {

        // This list represents all alerts generated by the hospital system
        List<Alert> alerts = new ArrayList<>();

        // Adding different types of alerts to simulate real hospital notifications
        alerts.add(new Alert("EMERGENCY", "Heart rate critical", 10));
        alerts.add(new Alert("MEDICATION", "Take insulin dose", 6));
        alerts.add(new Alert("APPOINTMENT", "Doctor visit at 10 AM", 3));
        alerts.add(new Alert("EMERGENCY", "Oxygen level low", 9));

        // User preference decides which alerts should be visible
        String userPreference = "PRIORITY";

        // Predicate will hold the filtering rule based on user preference
        Predicate<Alert> filterRule;

        /*
         * Based on the user preference, we dynamically assign
         * a filtering condition using lambda expressions.
         * Each lambda returns true or false for a given alert.
         */
        switch (userPreference) {

            // Show only emergency-related alerts
            case "EMERGENCY" ->
                filterRule = alert -> alert.type.equals("EMERGENCY");

            // Show only medication-related alerts
            case "MEDICATION" ->
                filterRule = alert -> alert.type.equals("MEDICATION");

            // Show alerts that are considered high priority
            case "HIGH_PRIORITY" ->
                filterRule = alert -> alert.priority >= 8;

            // Default case shows all alerts when no specific preference is matched
            default ->
                filterRule = alert -> true;
        }

        // Display which preference is currently applied
        System.out.println("Showing alerts based on preference: " + userPreference);

        // Stream processes each alert and applies the predicate to filter the output
        alerts.stream()
              .filter(filterRule)
              .forEach(System.out::println);
    }
}
